name: publish

on:
  schedule:
    - cron: "0 0 * * 5"
  workflow_dispatch:
    inputs:
      release_type:
        description: "`alpha` or `stable` release?"
        required: true
        default: "alpha"

jobs:
  build:
    env:
      RELEASE_TYPE: alpha
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'grouparoo/grouparoo' }}
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          fetch-depth: 0
      - name: Update ENV
        if: github.event.inputs.release_type != ''
        run: echo "RELEASE_TYPE=${{ github.event.inputs.release_type }}" >> $GITHUB_ENV
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: git config --global user.email "hello@grouparoo.com"
      - run: git config --global user.name "Grouparoo Bot"
      - run: npm install -g pnpm
      - name: publish
        run: ./bin/publish $RELEASE_TYPE
        env:
          GITHUB_AUTH: ${{ secrets.GH_ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
