name: publish

on:
  schedule:
    - cron: "0 0 * * 5"
  workflow_dispatch:
    inputs:
      release_type:
        description: "`alpha` or `stable` release?"
        required: true
        default: "alpha"

jobs:
  build:
    env:
      RELEASE_TYPE: alpha
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'grouparoo/grouparoo' }}
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      - name: Update ENV
        if: github.event.inputs.release_type != ''
        run: echo "RELEASE_TYPE=${{ github.event.inputs.release_type }}" >> $GITHUB_ENV
      - name: publish
        run: ./bin/publish $RELEASE_TYPE
